### ISSUE TITLE
How to build with stack?

### ISSUE THREAD

**Issue by glaukon-ariston** [Euterpea/Euterpea2#11]
How to build using stack with lts-7.19 and Haskell Platform 8.0.1 on Windows XP? I've tried with the following in stack.yaml, but I am getting errors:

```
resolver: lts-7.19
extra-deps:
  - Euterpea-2.0.2
  - PortMidi-0.1.5.2
  - heap-0.6.0
  - arrows-0.4.4.1
  - Stream-0.4.7.2
  - lazysmallcheck-0.6
```

The output is:

```
J:\dev\hp\projects\music>stack build
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:
      stm: needed (==2.4.2), 2.4.4.1 found (latest applicable is 2.4.2)
    needed for package Euterpea-2.0.2

--  Failure when adding dependencies:
      Euterpea: needed (-any), couldn't resolve its dependencies
    needed for package music-0.1.0.0
```

**Comment by donya** [comment]
Windows XP is unfortunately not an operating system that can still be guaranteed for Euterpea (Windows 7 is the oldest version actively supported at the moment). My last experiences working with that operating system showed an increasing number of problems as support moved on to later versions of GHC, and that was around 3 years ago. So, I don't know whether these issues are XP-related, Stack-related, or Euterpea-related. Package managers other than cabal are also not actively supported currently.
