### ISSUE TITLE
Euterpea2 does not work with latest packages

### ISSUE THREAD

**Issue by sternenseemann** [Euterpea/Euterpea2#16]
Trying to install `Euterpea` with `ghc-8.0.2` and the latest hackage package results in the following errors:

```
$ cabal update
Downloading the latest package list from hackage.haskell.org
$ cabal sandbox init
Writing a default package environment file to
/home/lukas/tmp/Euterpea2/cabal.sandbox.config
Creating a new sandbox at /home/lukas/tmp/Euterpea2/.cabal-sandbox
$  cabal install Euterpea
Resolving dependencies...
Notice: installing into a sandbox located at
/home/lukas/tmp/Euterpea2/.cabal-sandbox
Configuring heap-1.0.3...
Configuring PortMidi-0.1.5.2...
Configuring lazysmallcheck-0.6...
Configuring primitive-0.6.2.0...
Configuring random-1.1...
Configuring stm-2.4.4.1...
Building heap-1.0.3...
Building primitive-0.6.2.0...
Building stm-2.4.4.1...
Building lazysmallcheck-0.6...
Building random-1.1...
Failed to install PortMidi-0.1.5.2
Build log ( /home/lukas/tmp/Euterpea2/.cabal-sandbox/logs/ghc-8.0.2/PortMidi-0.1.5.2-4P9h5F665SYElLgBFZsRL6.log ):
cabal: Entering directory '/run/user/1000/cabal-tmp-12957/PortMidi-0.1.5.2'
Configuring PortMidi-0.1.5.2...
cabal: Missing dependency on a foreign library:
* Missing C library: asound
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
cabal: Leaving directory '/run/user/1000/cabal-tmp-12957/PortMidi-0.1.5.2'
Installed lazysmallcheck-0.6
Installed stm-2.4.4.1
Installed heap-1.0.3
Installed random-1.1
Installed primitive-0.6.2.0
cabal: Error: some packages failed to install:
Euterpea-2.0.4-9DWmfQtAXOW95kZGg8IJVr depends on Euterpea-2.0.4 which failed
to install.
PortMidi-0.1.5.2-4P9h5F665SYElLgBFZsRL6 failed during the configure step. The
exception was:
ExitFailure 1
```

The possible fix is widening the requirements for `stm` and `PortMidi` in `Euterpea.cabal`, so the most recent package versions also match:

```
        stm>=2.4.2 && <2.5,
        PortMidi>=0.1.5.3 && < 1.7,
```

This update breaks nothing in context with `stm` only the API change of PortMidi breaks Euterpea. The change is the change from `PMMsg` to `CLong` [here](https://hackage.haskell.org/package/PortMidi-0.1.6.1/docs/Sound-PortMidi.html#t:PMEvent). This, as a result, requires you to call [`decodeMsg`](https://hackage.haskell.org/package/PortMidi-0.1.6.1/docs/Sound-PortMidi.html#v:decodeMsg) and [`encodeMsg`](https://hackage.haskell.org/package/PortMidi-0.1.6.1/docs/Sound-PortMidi.html#v:encodeMsg) respectively.

The necessary change is [exactly my PR](https://github.com/Euterpea/Euterpea2/pull/14), you can view the necessary patch [here](https://github.com/Euterpea/Euterpea2/pull/14.patch) and apply it yourself (`git apply` or something).

**Comment by donya** [comment]
If you aren't using Euterpea 2.0.4, please update to that one and try again (you can use Hackage or GitHub; both are the same currently although they were different for some time). 

The changes from Euterpea 2.0.3 to 2.0.4 include a data structure change (Mode) and altered version ranges on several dependencies (more than stm) because of compatibility problems with the recently released 8.2.1, but PortMidi is not one of them yet (it will be addressed in a later update).

**Comment by sternenseemann** [comment]
It is a problem of both `master` and `2.0.4`, which I both tested.

**Comment by sternenseemann** [comment]
I've [updated my fix](https://github.com/Euterpea/Euterpea2/compare/master...sternenseemann:master).

**Comment by donya** [comment]
Can you give OS details?

**Comment by sternenseemann** [comment]
NixOS on [`master`](https://github.com/nixos/nixpkgs)
