### ISSUE TITLE
Why Literate Haskell?

### ISSUE THREAD

**Issue by FintanH** [Euterpea/Euterpea2#31]
I'm curious as to why all the files are Literate Haskell? Seems like a bit of a weird choice for a full on Haskell library. I also think it's stopping Hackage from generating any HTML for the docs 🤔

I'm having fun with Euterpea (just wrote the into to Street Spirit for fun), but it'd be easier to browse the library if there was documentation on Hackage. I'd love to help if possible :)

**Comment by donya** [comment]
The library was originally one and the same with the Haskell School of Music textbook, being compliable to a both library and a textbook using lhs2tex. While that worked while both components were relatively small, it eventually that became rather unwieldy for maintenance as the textbook components grew too large and started incorporating a lot of images (making for a big download), so the two were separated. The lhs format was left in place during this separation and not changed. 

Between the textbook and the website (euterpea.com) that has API descriptions and tutorials, there is a reasonable amount of documentation available on how to use Euterpea.

**Comment by FintanH** [comment]
Just as a follow up, would you be open to a PR that changed the files to `.hs` files? While I appreciate the textbook and the website, I think it would be useful to browse modules via a tool like Hoogle. Browsing the code base becomes easier this way. But if not then that's fine :)

Thanks for the reply!
