### ISSUE TITLE
Why do Staccato and Legato have the same implementation?

### ISSUE THREAD

**Issue by mverzilli** [Euterpea/Euterpea2#33]
Please let me know if this isn't the right place to ask! I didn't find any forums where these things could be discussed. 

I was playing with the library and was surprised to find that `(Staccato 2 1)` and `(Legato 2 1)` sounded the same. Then I took a look at the code and found out the implementations were actually equal. I thought, well, maybe the implementation is a bit behind? But then I downloaded the HSoM book and saw that the implementation described in the book is exactly that.

Is there any rationale behind this? As a musician, I'd expect "somewhat Staccato" to be different than "somewhat Legato".

Again, I apologize if this is not actually the right place to ask :).

**Comment by donya** [comment]
My response here is very late, but I believe Paul just viewed staccato and legato as semantic wrappers for note length modification where one is only used with large values and the other with small values. I wasn't involved much in the design of those data structures. Ultimately the interpretation of those types of performance annotations is meant to be handled by a Player (HSoM library, not Euterpea) in which case the user can supply their own interpretation by creating their own Player if they disagree with the default behaviors.
