### ISSUE TITLE
Installation fails with ghcup on OS X 10.14

### ISSUE THREAD

**Issue by donya** [Euterpea/Euterpea2#34]
Installing Euterpea with ghcup fails on OS X 10.14 (Mojave) with cabal version errors. I don't have a solution for ghcup at present but am looking into it.

Using an older version of Haskell Platform's dedicated installer (like 8.6.3) is one option as a workaround.

**Comment by donya** [comment]
Quickest solution seems to be to install this way:

cabal v1-install Euterpea

or just "cabal v1-install" for local copies of the repo.

**Comment by ksvanhorn** [comment]
mac> cabal --version
cabal-install version 1.22.6.0
using version 1.22.5.0 of the Cabal library
