### ISSUE TITLE
cabal install fails with ghc 8.8.1 or later

### ISSUE THREAD

**Issue by GeorgeCo** [Euterpea/Euterpea2#37]
cabal v1-install Euterpea
...
[2 of 7] Compiling Codec.ByteString.Parser ( src/Codec/ByteString/Parser.hs, dist/build/Codec/ByteString/Parser.o, dist/build/Codec/ByteString/Parser.dyn_o )

src/Codec/ByteString/Parser.hs:143:5: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
143 |     fail  err  = Parser $ \(S _ _ bytes) ->
    |     ^^^^
cabal: Leaving directory '/var/folders/df/5d_dsdrx1dn4j30ktsgn8blh0000gp/T/cabal-tmp-24877/HCodecs-0.5.1'
cabal: Error: some packages failed to install:

**Comment by donya** [comment]
Euterpea is only guaranteed through 8.6.5 right now. 

As far as possibly fixing this for later GHC versions, please provide:
- OS and version (bear in mind success can't be guaranteed on Linux regardless of GHC version)
- cabal version 
- the complete transcript of install commands leading to the failure at the end (please don't clip out portions of the log)

**Comment by GeorgeCo** [comment]
will update with that info later. Just wanted to note for reference that this error is expected with 8.8.1 or later. From https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.8

GHC 8.8 implements the final phase of the MonadFail proposal and now does the following:

The fail method of Monad has been removed in favor of the method of the same name in the MonadFail class.

MonadFail(..) is now exported from the Prelude and Control.Monad modules.
The MonadFailDesugaring language extension is now deprecated, as its effects are always enabled.

Also see https://gitlab.haskell.org/ghc/ghc/wikis/proposal/monad-fail#adapting-old-code

**Comment by donya** [comment]
From the limited error printout it appears to not be a problem in Euterpea's own code base but rather a dependency I don't have control over, in which case it needs to be reported for the repo of the affected package(s) (hence the request for full printout to be sure of which things are broken).

**Comment by GeorgeCo** [comment]
Right, sorry it is an error in the binary-bits package used by codec which is used by Euterpea. I will file a bug against binary-bits later.

**Comment by GeorgeCo** [comment]
Bug report mailed to maintainer of binary-bits package
