### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by madjestic** [Euterpea/Euterpea2#4]
When I start ghci and do:
`import Euterpea`
`play $ c 4 qn`
I hear no sound.
I can play midi files with timidity, I've got a midi-keyboard working with jack and qsynth, so midi setup should be ok, but still no sounds and no errors.

I would like to know how to debug it...

`madjestic@nu ~ $ ghci -V`
`The Glorious Glasgow Haskell Compilation System, version 7.10.3`

Thanks.

**Comment by donya** [comment]
Run "devices" and see what's listed; you may need to use "playDev" instead of "play" if output device 0 (the default) is not the one you configured.

**Comment by madjestic** [comment]
Than worked!  Thanks.

**Comment by donya** [comment]
Glad you have it working now.

For any others who happen upon this thread, additional troubleshooting and information for MIDI and playback in Euterpea is listed here: http://www.euterpea.com/euterpea/setting-up-midi/
