### ISSUE TITLE
Windows 10 Install fail

### ISSUE THREAD

**Issue by ChrLmb** [Euterpea/Euterpea2#42]
Using Win 10, Cabal 3.2.0.0, ghci 8.10.1, and with Avast turned off, I get the below.   Is the problem that   "... (constraint from minimum version of Cabal used by Setup.hs requires >=3.2)" and mine is 3.2.0.0?

**Thanks much for your help!**

Microsoft Windows [Version 10.0.18362.959]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\cxlam>cabal install Euterpea
Resolving dependencies...
cabal.exe: Could not resolve dependencies:
[__0] trying: Euterpea-2.0.7 (user goal)
[__1] next goal: Euterpea:setup.Cabal (dependency of Euterpea)
[__1] rejecting: Euterpea:setup.Cabal-3.2.0.0/installed-3.2.0.0 (conflict:
Euterpea => Euterpea:setup.Cabal>=1.8 && <1.25)
[__1] skipping: Euterpea:setup.Cabal-3.2.0.0, Euterpea:setup.Cabal-3.0.2.0,
Euterpea:setup.Cabal-3.0.1.0, Euterpea:setup.Cabal-3.0.0.0,
Euterpea:setup.Cabal-2.4.1.0, Euterpea:setup.Cabal-2.4.0.1,
Euterpea:setup.Cabal-2.4.0.0, Euterpea:setup.Cabal-2.2.0.1,
Euterpea:setup.Cabal-2.2.0.0, Euterpea:setup.Cabal-2.0.1.1,
Euterpea:setup.Cabal-2.0.1.0, Euterpea:setup.Cabal-2.0.0.2 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '>=1.8 && <1.25' from 'Euterpea')
[__1] rejecting: Euterpea:setup.Cabal-1.24.2.0, Euterpea:setup.Cabal-1.24.0.0,
Euterpea:setup.Cabal-1.22.8.0, Euterpea:setup.Cabal-1.22.7.0,
Euterpea:setup.Cabal-1.22.6.0, Euterpea:setup.Cabal-1.22.5.0,
Euterpea:setup.Cabal-1.22.4.0, Euterpea:setup.Cabal-1.22.3.0,
Euterpea:setup.Cabal-1.22.2.0, Euterpea:setup.Cabal-1.22.1.1,
Euterpea:setup.Cabal-1.22.1.0, Euterpea:setup.Cabal-1.22.0.0,
Euterpea:setup.Cabal-1.20.0.4, Euterpea:setup.Cabal-1.20.0.3,
Euterpea:setup.Cabal-1.20.0.2, Euterpea:setup.Cabal-1.20.0.1,
Euterpea:setup.Cabal-1.20.0.0, Euterpea:setup.Cabal-1.18.1.7,
Euterpea:setup.Cabal-1.18.1.6, Euterpea:setup.Cabal-1.18.1.5,
Euterpea:setup.Cabal-1.18.1.4, Euterpea:setup.Cabal-1.18.1.3,
Euterpea:setup.Cabal-1.18.1.2, Euterpea:setup.Cabal-1.18.1.1,
Euterpea:setup.Cabal-1.18.1, Euterpea:setup.Cabal-1.18.0,
Euterpea:setup.Cabal-1.16.0.3, Euterpea:setup.Cabal-1.16.0.2,
Euterpea:setup.Cabal-1.16.0.1, Euterpea:setup.Cabal-1.16.0,
Euterpea:setup.Cabal-1.14.0, Euterpea:setup.Cabal-1.12.0,
Euterpea:setup.Cabal-1.10.2.0, Euterpea:setup.Cabal-1.10.1.0,
Euterpea:setup.Cabal-1.10.0.0, Euterpea:setup.Cabal-1.8.0.6,
Euterpea:setup.Cabal-1.8.0.4, Euterpea:setup.Cabal-1.8.0.2,
Euterpea:setup.Cabal-1.6.0.3, Euterpea:setup.Cabal-1.6.0.2,
Euterpea:setup.Cabal-1.6.0.1, Euterpea:setup.Cabal-1.4.0.2,
Euterpea:setup.Cabal-1.4.0.1, Euterpea:setup.Cabal-1.4.0.0,
Euterpea:setup.Cabal-1.2.4.0, Euterpea:setup.Cabal-1.2.3.0,
Euterpea:setup.Cabal-1.2.2.0, Euterpea:setup.Cabal-1.2.1,
Euterpea:setup.Cabal-1.1.6, Euterpea:setup.Cabal-1.24.1.0 (constraint from
minimum version of Cabal used by Setup.hs requires >=3.2)
[__1] fail (backjumping, conflict set: Euterpea, Euterpea:setup.Cabal)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: Euterpea:setup.Cabal, Euterpea

**Comment by donya** [comment]
Euterpea on Hackage is currently not compatible past GHC 8.6.5.

**Comment by ChrLmb** [comment]
Thanks Donya!  I'll see about installing GHC 8.6.5.

**Comment by ChrLmb** [comment]
Thanks again.  I should have noticed the 8.6.5 requirement, which is now
installed and passes the 'play' test.
If I may: do you consider *The Haskell School of Music *to be the best way
to proceed?
I have a slender background in music, and, though not a gifted programmer,
I have several years experience with the functional language Mathematica.
Thanks for your time,

Christopher
