### ISSUE TITLE
Minor issue: ExportMidiFile.to7Bits generates suspect encoding

### ISSUE THREAD

**Issue by brianavid** [Euterpea/Euterpea2#5]
The delta times generated by `ExportMidiFile.to7Bits`represent zero as`[0x80, 0x00]` and indeed every small value starts with a spurious `0x80`. This is not defined by the Midi file spec, and generally you can get away with it. But loading into Anvil Studio, the file is reported as “corrupt” and has to be manually repaired.

The (tested) fix is trivial – the parameter to `padTo`within function `to7Bits`should always be 7 and not 8.

**Comment by donya** [comment]
This should be fixed now although I can't test with the particular software in question.
