### ISSUE TITLE
Cannot Install Euterpea on Windows

### ISSUE THREAD

**Issue by mspandit** [Euterpea/Euterpea2#56]
Operating System: Microsoft Windows 11 Home Version 22H2, OS Build 22621.2428
GHC version: 9.4.7
cabal version: 3.6.2.0

The instructions at https://www.euterpea.com/ say to use `cabal v1-update` but this leads to

```
cabal-3.6.2.0.exe: unrecognised command: v1-update (try --help)
Maybe you meant `v2-update`?
```

`cabal v2-update` works. 

However, the following error occurs on both `cabal v1-install` and `cabal v2-install`:

```
Resolving dependencies...
cabal-3.6.2.0.exe: Could not resolve dependencies:
[__0] trying: Euterpea-2.0.8 (user goal)
[__1] next goal: bytestring (dependency of Euterpea)
[__1] rejecting: bytestring-0.11.5.2/installed-0.11.5.2 (conflict: Euterpea =>
bytestring>=0.10.4.0 && <=0.10.9)
[__1] skipping: bytestring-0.12.0.2, bytestring-0.12.0.1, bytestring-0.12.0.0,
bytestring-0.11.5.2, bytestring-0.11.5.1, bytestring-0.11.5.0,
bytestring-0.11.4.0, bytestring-0.11.3.1, bytestring-0.11.3.0,
bytestring-0.11.2.0, bytestring-0.11.1.0, bytestring-0.11.0.0,
bytestring-0.10.12.1, bytestring-0.10.12.0, bytestring-0.10.10.1,
bytestring-0.10.10.0, bytestring-0.10.9.0 (has the same characteristics that
caused the previous version to fail: excluded by constraint '>=0.10.4.0 &&
<=0.10.9' from 'Euterpea')
[__1] trying: bytestring-0.10.8.2
[__2] next goal: base (dependency of Euterpea)
[__2] rejecting: base-4.17.2.0/installed-4.17.2.0 (conflict: bytestring =>
base>=4.2 && <4.15)
[__2] skipping: base-4.19.0.0, base-4.18.1.0, base-4.18.0.0, base-4.17.2.0,
base-4.17.1.0, base-4.17.0.0, base-4.16.4.0, base-4.16.3.0, base-4.16.2.0,
base-4.16.1.0, base-4.16.0.0, base-4.15.1.0, base-4.15.0.0 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '>=4.2 && <4.15' from 'bytestring')
[__2] rejecting: base-4.14.3.0, base-4.14.2.0, base-4.14.1.0, base-4.14.0.0,
base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0, base-4.10.1.0,
base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0, base-4.8.1.0,
base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0, base-4.6.0.1,
base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0, base-4.4.0.0,
base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1, base-4.2.0.0,
base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (constraint from
non-upgradeable package requires installed instance)
[__2] fail (backjumping, conflict set: Euterpea, base, bytestring)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, bytestring, Euterpea
```

**Comment by donya** [comment]
Did you try the --allow-newer flag with the cabal install? If not, try that
first:
cabal v1-install --allow-newer

**Comment by nj-watkins** [comment]
I also cannot install on Windows, and am using 
```
cabal v1-install --allow-newer
```
It seems like there are errors in building the dependences: semigroups-0.20, lazysmallcheck-0.6, heap-1.0.4, splitmix-0.1.0.5, PortMidi-0.2.0.0

Will try to install the above individually first.  New to Haskell, but sometimes that works with Python/pip

**Comment by donya** [comment]
I will go ahead and close this for now since the install was working but wanted to add a note that I will be investigating installs with >8.10 on Windows soon (having now seen a successful but not well tested install with 9.something on a Mac) although I don't have a Win11 machine specifically to test on (my machines are Win10), so one thing I wont' be able to rule out going forward checkinng >8.10 on Win is whether 10 vs 11 was one of the factors here.

**Comment by donya** [comment]
Looks like it may simply be "cabal update" on 9.x...yet then still using "v1-install" for the actual installation. I just got a successful install with 9.0.1 on Windows with that approach (same for HSoM, also tested playback and MUIs which are fine). I will update the installation instructions; looks like v1-update is not needed even for 8.x after some tests.
