### ISSUE TITLE
Design issue: Cannot handle same notes on separate “tracks”

### ISSUE THREAD

**Issue by brianavid** [Euterpea/Euterpea2#7]
My first attempt to use Euterpea to transcribe some simple piano music resulted in a corrupt Midi file with badly interleaved NoteOn and NoteOff events for the same note. It took me quite a while to understand this with a couple of false analyses [_Sorry Donya for the spurious mails_]. But the outcome shows a problem in the underlying Euterpea modelling of note-level music such that any fix would unfortunately be pervasive through the book!

The particular problem example is illustrated by the attached music image and Haskell file. In bar 2 left hand, there is a D held for much of the bar. But the right had also plays that same D at the same time. This is a common piano idiom. When the music is exported as a Midi file, the NoteOn/NoteOff events are then incorrectly interleaved. This can be seen in the text dump of the Midi file – search for occurrences of “d4”. 

- [nortonpreludeii](https://cloud.githubusercontent.com/assets/5159216/14679861/8e4ac64a-0713-11e6-9867-1c631da2f10a.JPG)
- [NortonPreludeII-Broken.hs.txt](https://github.com/Euterpea/Euterpea2/files/228215/NortonPreludeII-Broken.hs.txt)
- [TEST.TXT](https://github.com/Euterpea/Euterpea2/files/228208/TEST.TXT)

The underlying problem is the lack of a model for separate tracks, which are independent sequences of played notes. The aggregation of the music into an amorphous “bucket of notes” which are then split into one track per instrument does not work in this case. Unfortunately, this is not the same note-level model as is used by Midi.

I could consider a fix for this particular case which “fixes up” the NoteOn and NoteOff for each note such that it becomes well formed, while preserving the timing. But that would be a fix only for limited cases – for example it would not work for a two piano piece or a string quartet with two violins.

So I wonder if it is too late to consider a change of the Music model in Euterpea to add the concept of a “track” Is this something that could be added through a new Control?

The simplest solution I can think of is to change the `Instrument` `Control` constructor to take a parameter of type `(InstrumentName, String)`, where the second component of the tuple is a track name, such as “Left hand” or “2nd fiddle”. The `instrument` function then becomes 
`instrument i m  = Modify (Instrument (i, i)) m`
and we have a new function
`instrumentTrack i n m  = Modify (Instrument (i, n)) m`
Rippling through the dependencies should then be easy as the compiler will pick them all up. And the only consequential functional change will be in the `ToMidi` construction of the `UserPatchMap`.

Does the problem make sense? Is the proposed solution worthwhile? I realize that it will still have some implication of the text of the book which explains the existing code.

**Comment by donya** [comment]
You are correct that this is a limitation of Euterpea's representations, but there are no plans to alter or extend the Music data structures and associated central features of the library. If you have a specific need for this extra functionality I would suggest making a modified version of the library specific to your needs.
