### ISSUE TITLE
support for SuperCollider

### ISSUE THREAD

**Issue by tpltnt** [Euterpea/Euterpea2#8]
Hi there,

as a practitioner of creative (live) coding I would like to have [SuperCollider](https://wiki.haskell.org/SuperCollider) support (and not only MIDI and CSound). I would love to use Haskell for creative endeavours, but Overtone is really tempting given its feature set.

Cheers,
tpltnt

**Comment by donya** [comment]
There are some SuperCollider bindings for Haskell like hsc3. There are currently no plans to add SuperCollider compatibility to Euterpea though.
