### ISSUE TITLE
reading MIDI to play difficulties

### ISSUE THREAD

**Issue by flofehrenbacher** [Euterpea/Euterpea2#9]
Hello there,

I am currently working on a project where I am using Euterpea2. I try to read the MIDI signals and then play the corresponding note. (see below) Instead of reading the note only when play would "need" it, it is all the time reading and therefore never playing. When I try to call play everytime I get MIDI signals I get warnings that devices were left open. (also attached) Do you have any suggestion how to deal with this issue?

Thanks in advance!
Cheers, Florian

![readandplay](https://cloud.githubusercontent.com/assets/18660708/15979659/ae9824ea-2f65-11e6-85b0-d78e62cd9404.jpg)

![warning](https://cloud.githubusercontent.com/assets/18660708/15979782/72734d86-2f66-11e6-9e41-6c48f0c99822.jpg)

**Comment by donya** [comment]
I can't diagnose incomplete code such as this in any detail. However, I can say that you should not use "play" to do real-time interactive work involving a MIDI input device. You do indeed need to poll the input device constantly to check whether messages have been queued, and then if they exist you can process them accordingly. Please see the following program for an example of how to rout MIDI messages between devices in real time:

http://www.donyaquick.com/files/HaskellOx4.zip

The zip contains both the source, a compiled Windows executable, and a batch file showing the best compilation commands.

**Comment by flofehrenbacher** [comment]
Thank you very much for answering that fast!
